// export const bookGenres = {
//     fiction: 'fiction',
//     history: 'history',
//     mystery: 'mystery',
//     'sci-fi': 'sci-fi',
//     biography: 'biography',
//     'young-adult-fiction': 'young-adult-fiction',
//     romance: 'romance',
//     childrens: 'childrens',
//     'self-help': 'self-help',
//     fantasy: 'fantasy',
//     poetry: 'poetry',
//     cookbook: 'cookbook',
//     'social-science': 'social-science',
//     travel: 'travel',
//     'reference-study': 'reference-study',
//     photography: 'photography',
//     business: 'business',
//     technology: 'technology',
//     politics: 'politics'
// };
