// export const cellCarriers = {
//     'AT&T WirelessAT&T Wireless': 'AT&T WirelessAT&T Wireless',
//     'Blue WirelessBlue Wireless': 'Blue WirelessBlue Wireless',
//     'Boost MobileBoost Mobile': 'Boost MobileBoost Mobile',
//     'Consumer CellularConsumer Cellular': 'Consumer CellularConsumer Cellular',
//     'Cricket WirelessCricket Wireless': 'Cricket WirelessCricket Wireless',
//     'H2O WirelessH2O Wireless': 'H2O WirelessH2O Wireless',
//     'Net10 WirelessNet10 Wireless': 'Net10 WirelessNet10 Wireless',
//     'Simple MobileSimple Mobile': 'Simple MobileSimple Mobile',
//     SprintSprint: 'SprintSprint',
//     'Straight TalkStraight Talk': 'Straight TalkStraight Talk',
//     'T-MobileT-Mobile': 'T-MobileT-Mobile',
//     TingTing: 'TingTing',
//     'Total WirelessTotal Wireless': 'Total WirelessTotal Wireless',
//     'TracFone WirelessTracFone Wireless': 'TracFone WirelessTracFone Wireless',
//     UnlockedUnlocked: 'UnlockedUnlocked',
//     UScellularUScellular: 'UScellularUScellular',
//     'Verizon WirelessVerizon Wireless': 'Verizon WirelessVerizon Wireless',
//     'Virgin MobileVirgin Mobile': 'Virgin MobileVirgin Mobile'
// };
