// export const closureTypes = {
//     backstrap: 'backstrap',
//     buckle: 'buckle',
//     bungee: 'bungee',
//     button: 'button',
//     clip: 'clip',
//     drawstring: 'drawstring',
//     'half-zip': 'half-zip',
//     'hook & bar': 'hook & bar',
//     'hook & eye': 'hook & eye',
//     'hook & loop': 'hook & loop',
//     'lace-up': 'lace-up',
//     magnetic: 'magnetic',
//     'pull-on': 'pull-on',
//     'slip-on': 'slip-on',
//     snap: 'snap',
//     'speed laces': 'speed laces',
//     tie: 'tie',
//     zipper: 'zipper'
// };
