export const detailsTypes = {
    'apparel-bottoms': 'apparel-bottoms',
    'apparel-bras': 'apparel-bras',
    'apparel-footwear': 'apparel-footwear',
    'apparel-tops': 'apparel-tops',
    apparel: 'apparel',
    'cables-data': 'cables-data',
    'cables-power': 'cables-power',
    'cables-video': 'cables-video',
    cables: 'cables',
    'cell-phones': 'cell-phones',
    'computer-components': 'computer-components',
    'computer-components-drives': 'computer-components-drives',
    'computer-components-ram': 'computer-components-ram',
    'computer-components-other': 'computer-components-other',
    electronics: 'electronics',
    general: 'general',
    'home-goods-dinnerware': 'home-goods-dinnerware',
    'home-goods-flatware': 'home-goods-flatware',
    'home-goods': 'home-goods',
    jewelry: 'jewelry',
    'kitchen-appliances': 'kitchen-appliances',
    'media-books': 'media-books',
    'media-music': 'media-music',
    'media-video-games': 'media-video-games',
    'media-videos-film': 'media-videos-film',
    'media-videos-tv-series': 'media-videos-tv-series',
    'media-videos': 'media-videos',
    media: 'media',
    'sporting-goods-golf-clubs': 'sporting-goods-golf-clubs',
    'sporting-goods': 'sporting-goods',
    toys: 'toys'
};

// console.log(Object.keys(detailsTypes).map(x => `'${x}' | `).join(''));