import { createMRTColumnHelper, MRT_ColumnDef } from 'material-react-table';
import { addressColumns } from './columns/address';
import { attributeColumns } from './columns/attribute';
import { auctionColumns } from './columns/auction';
import { col } from './defs/col';
import { barcodeColumns } from './columns/barcode';
import { includedItemColumns } from './columns/includedItem';
import { productColumns } from './entity/productColumns';
import { sku } from './columns/sku';
import { facing } from './columns/facing';
import { facilityColumns } from './columns/facility';
import { binColumns } from './columns/bin';
import { brandColumns } from './columns/brand';
import { classifierColumns } from './columns/classifier';
import { clothingCareColumns } from './columns/clothingCare';
import { connectorColumns } from './columns/connector';
import { currentSettingColumns } from './columns/currentSetting';
import { customItemFieldColumns } from './columns/customItemField';
import { shippingColumns } from './columns/shipping';
import { hashTagColumns } from './columns/hashTag';
import { hashTagUsageColumns } from './columns/hashTagUsage';
import { madeOfSectionColumns } from './columns/madeOfSection';
import { mercariBrandColumns } from './columns/mercariBrand';
import { mercariCategoryColumns } from './columns/mercariCategory';
import { mercariTaxonomyColumns } from './columns/mercariTaxonomy';
import { minMaxColumns } from './columns/minMax';
import { selfStorageColumns } from './columns/selfStorage';
import { productImage } from './columns/productImage';
import { squareFootageColumns } from './columns/squareFootage';
import { trackColumns } from './columns/track';
import { apparelBottoms, apparelBras, apparelDetails, apparelFootwear, apparelTops } from './entity/details/apparelDetails';
import { mediaBooksDetails, mediaDetails, mediaMusicDetails, mediaVideoGameDetails, mediaVideosDetails } from './entity/details/mediaDetails';
import { cablesDetails, cablesPowerDetails, cablesVideoDetails, cablesDataDetails } from './entity/details/cablesDetails';
import { cellPhonesDetails } from './entity/details/cellPhoneDetails';
import { electronicsDetails } from './entity/details/electronicsDetails';
import { generalDetails } from './entity/details/generalDetails';
import { homeGoodsDetails, homeGoodsFlatwareDetails, homeGoodsDinnerwareDetails } from './entity/details/homeGoodsDetails';
import { jewelryDetails } from './entity/details/jewelryDetails';
import { kitchenAppliancesDetails } from './entity/details/kitchenAppliancesDetails';
import { sportingGoodsDetails, sportingGoodsGolfClubsDetails } from './entity/details/sportingGoodsDetails';
import { toysDetails } from './entity/details/toysDetails';
import { pieceColumns } from './columns/piece';
import { draftColumns } from './columns/draft';
import { computerComponentsDetails, computerComponentsDrivesDetails, computerComponentsRamDetails } from './entity/details/computerComponentsDetails';
import { dimension } from './columns/dimension';

const h = createMRTColumnHelper<{ value: any }>();
const helper = col(h);
const stringColumn = helper.string('value', 'Value', undefined, { required: true });
const intColumn = helper.int('value', 'Value', { required: true });
const doubleColumn = helper.double('value', 'Value', { required: true });
const boolColumn = helper.bool('value', 'Value');
const dateColumn = helper.date('value', 'Value', {}, true);

// (Realm.ObjectSchema | Realm.ObjectClass<any>)

if (window.columns == null) window.columns = {};
window.columns.string = [stringColumn] as MRT_ColumnDef<any>[];
window.columns.int = [intColumn] as MRT_ColumnDef<any>[];
window.columns.double = [doubleColumn] as MRT_ColumnDef<any>[];
window.columns.date = [dateColumn] as MRT_ColumnDef<any>[];
window.columns.bool = [boolColumn] as MRT_ColumnDef<any>[];
// window.columns. = [Column] as MRT_ColumnDef<any>[];

window.columns.address = addressColumns as MRT_ColumnDef<any>[];
window.columns.attribute = attributeColumns as MRT_ColumnDef<any>[];
window.columns.auction = auctionColumns as MRT_ColumnDef<any>[];
window.columns.barcode = barcodeColumns as MRT_ColumnDef<any>[];
window.columns.bin = binColumns as MRT_ColumnDef<any>[];
window.columns.brand = brandColumns as MRT_ColumnDef<any>[];
window.columns.classifier = classifierColumns as MRT_ColumnDef<any>[];
window.columns.clothingCare = clothingCareColumns as MRT_ColumnDef<any>[];
window.columns.connector = connectorColumns as MRT_ColumnDef<any>[];
window.columns.currentSetting = currentSettingColumns as MRT_ColumnDef<any>[];
window.columns.customItemField = customItemFieldColumns as MRT_ColumnDef<any>[];
window.columns.facility = facilityColumns as MRT_ColumnDef<any>[];
window.columns.hashTag = hashTagColumns as MRT_ColumnDef<any>[];
window.columns.hashTagUsage = hashTagUsageColumns as MRT_ColumnDef<any>[];
window.columns.includedItem = includedItemColumns as MRT_ColumnDef<any>[];
window.columns.madeOfSection = madeOfSectionColumns as MRT_ColumnDef<any>[];
window.columns.mercariBrand = mercariBrandColumns as MRT_ColumnDef<any>[];
window.columns.mercariCategory = mercariCategoryColumns as MRT_ColumnDef<any>[];
window.columns.mercariTaxonomy = mercariTaxonomyColumns as MRT_ColumnDef<any>[];
window.columns.minMax = minMaxColumns as MRT_ColumnDef<any>[];
window.columns.product = productColumns as MRT_ColumnDef<any>[];
window.columns.productFacing = facing as MRT_ColumnDef<any>[];
window.columns.productImage = productImage as MRT_ColumnDef<any>[];
window.columns.selfStorage = selfStorageColumns as MRT_ColumnDef<any>[];
window.columns.shipping = shippingColumns as MRT_ColumnDef<any>[];
window.columns.sku = sku as MRT_ColumnDef<any>[];
window.columns.squareFootage = squareFootageColumns as MRT_ColumnDef<any>[];
window.columns.track = trackColumns as MRT_ColumnDef<any>[];

window.columns.apparelDetails = apparelDetails as MRT_ColumnDef<any>[];
window.columns.apparelBottomsDetails = apparelBottoms as MRT_ColumnDef<any>[];
window.columns.apparelTopsDetails = apparelTops as MRT_ColumnDef<any>[];
window.columns.apparelBrasDetails = apparelBras as MRT_ColumnDef<any>[];
window.columns.apparelFootwearDetails = apparelFootwear as MRT_ColumnDef<any>[];
window.columns.mediaDetails = mediaDetails as MRT_ColumnDef<any>[];
window.columns.mediaBookDetails = mediaBooksDetails as MRT_ColumnDef<any>[];
window.columns.mediaMusicDetails = mediaMusicDetails as MRT_ColumnDef<any>[];
window.columns.mediaVideoDetails = mediaVideosDetails as MRT_ColumnDef<any>[];
window.columns.mediaVideoGameDetails = mediaVideoGameDetails as MRT_ColumnDef<any>[];
window.columns.generalDetails = generalDetails as MRT_ColumnDef<any>[];
window.columns.homeGoodsDetails = homeGoodsDetails as MRT_ColumnDef<any>[];
window.columns.homeGoodsFlatwareDetails = homeGoodsFlatwareDetails as MRT_ColumnDef<any>[];
window.columns.homeGoodsDinnerwareDetails = homeGoodsDinnerwareDetails as MRT_ColumnDef<any>[];
window.columns.electronicsDetails = electronicsDetails as MRT_ColumnDef<any>[];
window.columns.cellPhonesDetails = cellPhonesDetails as MRT_ColumnDef<any>[];
window.columns.sportingGoodsDetails = sportingGoodsDetails as MRT_ColumnDef<any>[];
window.columns.sportingGoodsGolfClubsDetails = sportingGoodsGolfClubsDetails as MRT_ColumnDef<any>[];
window.columns.toysDetails = toysDetails as MRT_ColumnDef<any>[];
window.columns.jewelryDetails = jewelryDetails as MRT_ColumnDef<any>[];
window.columns.cablesDetails = cablesDetails as MRT_ColumnDef<any>[];
window.columns.cablesPowerDetails = cablesPowerDetails as MRT_ColumnDef<any>[];
window.columns.cablesVideoDetails = cablesVideoDetails as MRT_ColumnDef<any>[];
window.columns.cablesDataDetails = cablesDataDetails as MRT_ColumnDef<any>[];
window.columns.kitchenAppliancesDetails = kitchenAppliancesDetails as MRT_ColumnDef<any>[];
window.columns.piece = pieceColumns as MRT_ColumnDef<any>[];
window.columns.draft = draftColumns as MRT_ColumnDef<any>[];
window.columns.computerComponentsDetails = computerComponentsDetails as MRT_ColumnDef<any>[];
window.columns.computerComponentsDrivesDetails = computerComponentsDrivesDetails as MRT_ColumnDef<any>[];
window.columns.computerComponentsRamDetails = computerComponentsRamDetails as MRT_ColumnDef<any>[];

window.columns.dimension = dimension as any;
